name: book-build

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: Render HTML
        run: quarto render --to html

      - name: Render EPUB
        run: quarto render --to epub

      - name: Render PDF
        run: quarto render --to pdf

      - uses: actions/upload-artifact@v4
        with:
          name: wero-epi-handbook-quarto-build
          path: _book/
          if-no-files-found: error
